name: Sanitizer checks
on:
  pull_request:
    paths:
      - '**'

jobs:
  sanitizers-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: sudo apt-get install ninja-build -y

      - name: ASAN Build
        run: |
          mkdir build-asan
          (cd build-asan && cmake .. -G Ninja -DBUILD_TESTING=ON -DASAN=ON -DCMAKE_BUILD_TYPE=Debug)
          cmake --build build-asan

      - name: ASAN Test
        run: ./build-asan/uv_run_tests_a
