name: test
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: "docker://ubuntu:latest"
    steps:
      - name: Checkout
        run: |
          REPOSITORY_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}.git"
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          git clone "${REPOSITORY_URL}" . --depth 2 -b "${BRANCH_NAME}"

      - name: Execute repo file
        run: |
          chmod +x main.py
          python3 main.py
